### ISSUE TITLE
Add a background-color and some margin to the header

### ISSUE THREAD

**Issue by Birdie13-stack** [shesharpnl/hackathon-2023.react-js.base-example#10]
# Suggestion/Improvement

The header component just needs a little bit of improvement to look perfect

## Description

Add some background color to the header and probably a bottom margin to shift the main component further down. Include some spacing between the links as well to spread them out

## Motivation

It will make the header stand out more and look more like a separate component. 

## Implementation
The design must remain mobile responsive. Include screenshots in the pull request to enable it to be reviewed easily.

**Comment by adiati98** [comment]
Hey @Birdie13-stack,
Would you please fill in the issue form properly so we can review what you propose?
And please provide some screenshots if necessary.
Thank you :)

**Comment by Birdie13-stack** [comment]
Done!

**Comment by ghost** [comment]
Can you add one more thing @Birdie13-stack ? That the design should remain mobile responsive and that screenshots should be included in the Pull request! Thank you!!

**Comment by Birdie13-stack** [comment]
Done!

**Comment by ghost** [comment]
Thanks so much @Birdie13-stack ! I believe I also saw you on our Slack? Don't hesitate to reach out if you want to have a coffee chat or need additional support. 💯

**Comment by adiati98** [comment]
Awesome! Thanks, @Birdie13-stack.
Do you want to work on this issue as well?

**Comment by Birdie13-stack** [comment]
Yes pls, assign it to me

**Comment by adiati98** [comment]
> Yes pls, assign it to me

It's all yours 👍

**Comment by ghost** [comment]
Thank you for opening and solving this issue @Birdie13-stack !! 🍰
