### ISSUE TITLE
Add Contact Form 

### ISSUE THREAD

**Issue by ToobaJamal** [shesharpnl/hackathon-2023.react-js.base-example#13]
# Suggestion/Improvement

🌟 Use react.js to create a form component.

## Description

Create a contact form that can be edited by the project users according to their requirements. Add the form to the contact page linked to the contact menu item in the header/ navigation.

## Motivation

With all the other necessary components in the starter template available, adding a contact form will make it even better.

## Implementation (if applicable)

Make the form accessible, responsive and well-styled. Include a screenshot in the pull request.

**Comment by ghost** [comment]
Great issue @ToobaJamal ! Would you like to be assigned?

**Comment by ToobaJamal** [comment]
> Great issue @ToobaJamal ! Would you like to be assigned?
@mariahlaqua 
Yes, please :)

**Comment by kaushikgoud5** [comment]
Would you like to be assigned?
