### ISSUE TITLE
Add a router to the website

### ISSUE THREAD

**Issue by ocsiddisco** [shesharpnl/hackathon-2023.react-js.base-example#20]
## Description

Currenty the 'routing' is done with opening or closing a component with useState. As there is no 'about' component, nothing is happening when clicking on 'about'. A prettier solution would be adding a routing with a routine tool.

## Motivation

It will help junior developer creating a website with routing more easily as they will already have a menu working.

## Implementation (if applicable)

https://reactrouter.com/en/main/routers/create-browser-router

**Comment by ghost** [comment]
Whoop whoop, thanks @ocsiddisco Céline, would you like to be assigned?

**Comment by ocsiddisco** [comment]
yes please :)

**Comment by ghost** [comment]
@ocsiddisco If you have energy and time to update the ReadMe, including screenshots and a bit about the router, that would be great. If you don't have energy, just let me know, and I will create an issue for it. Thanks so much!!

**Comment by ghost** [comment]
Thanks @ocsiddisco for taking care of this, and for taking the extra time to give the README some love. 👍 💯
