### ISSUE TITLE
Create a header component.

### ISSUE THREAD

**Issue by ghost** [shesharpnl/hackathon-2023.react-js.base-example#6]
# Suggestion/Improvement

🌟 Use react.js to create a header and/or navigation component.

## Description

Visually and functionally improve the starter template. Code should be beginner friendly with helpful structure and comments.

## Motivation

The current UI of the template is boring, let's give Hackathon participants a nicer starting point.

## Implementation (if applicable)

Create a header component and render it on the app's index. Please include a screenshot with your pull request.

**Comment by ToobaJamal** [comment]
Hey, I would like to create the header component :)

**Comment by ghost** [comment]
@ToobaJamal Thanks for your interest! Please don't hesitate to reach out if you have questions, or join our #devs or #open-source channels on the [SheSharp Slack!](https://www.shesharp.co/slack)

**Comment by Birdie13-stack** [comment]
Hey, I would like to create the header component!

**Comment by ghost** [comment]
Hi @Birdie13-stack thank you! We have another issue open for a footer component, as @ToobaJamal is already assigned to the header. Maybe making the footer is interesting for you? Otherwise feel free to raise an issue of another component / feature / improvement you would like to make!

**Comment by Birdie13-stack** [comment]
I would love to start work on the footer right away as well as explore other features that need improvement. Please assign it to me

**Comment by ghost** [comment]
Thanks @Birdie13-stack ! I've assigned you the footer component issue. If you want to make other UI components it's helpful to raise an issue first, so we understand the goal. Excited to see what you build :) Please don't hesitate to reach out to us for support.

**Comment by ToobaJamal** [comment]
Hi @mariahlaqua, I see a "body" tag in App.jsx file which I believe is not appropriate as we already have a "body" Tag in index.html. Should I care about fixing that or just focus on adding the Header component? Thanks

**Comment by ghost** [comment]
@ToobaJamal do as you prefer, any improvements are welcome and fixing something is certainly appreciated. It's up to you and how much energy you have. Thank you for asking!

**Comment by ghost** [comment]
Big thank you to @ToobaJamal for creating this component!
