### ISSUE TITLE
Create a footer component

### ISSUE THREAD

**Issue by ghost** [shesharpnl/hackathon-2023.react-js.base-example#8]
# Suggestion/Improvement

🌟 Currently this starter template is lacking in terms of UI! Let's make it a bit nicer.

## Description

Create a footer component. Consider including some basic info, like links to the SheSharp website and socials, a copyright, maybe a link to the repo itself! Use helpful inline commenting to give context to your code.

## Motivation

We want our Hackathon starter templates to feel more complete.

## Implementation (if applicable)

The more accessible, the better. Bonus points for making the footer responsive and well-stylized. Please try to avoid adding additional dependencies, as this project is meant for beginners.

## Your Participation Matters

We appreciate your efforts to make this project more awesome! Your suggestions are valuable to us, and we'll review them as soon as possible. Please note that we prioritize our community members in assigning and approving pull requests.
-->

**Comment by Birdie13-stack** [comment]
I will like to work on this, please assign it to me

**Comment by ghost** [comment]
Excellent, thank you @Birdie13-stack ! Please don't hesitate to reach out to me or our community on [Slack](https://www.shesharp.co/slack) if you have questions. :)

**Comment by tutrinh16** [comment]
Hey there! Can you assign me.

**Comment by ghost** [comment]
Hi @tutrinh16 this is already assigned. :)

**Comment by ghost** [comment]
Completed by @Birdie13-stack !
